# Generated by Django 3.2.7 on 2024-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siterating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Very poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Very good'), (6, '6 - Excellent'), (7, '7 - Outstanding'), (8, '8 - Exceptional'), (9, '9 - Amazing'), (10, '10 - Perfect')], default=1)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
